#!/usr/bin/python3

import argparse
import sys
import os
import subprocess

def add_args(a):
  parser = argparse.ArgumentParser(description="BactCore")
  parser.add_argument(
    "--proc",
    help="Number of processes. Default: 1",
    type=int,
  )
  parser.add_argument(
    "--lowmem",
    "-lm",
    help="Run in low memory mode.",
    action=argparse.BooleanOptionalAction,
    default=False,
    required=False
  )
  parser.add_argument(
    "--strict",
    "-s",
    help="Run in low memory mode.",
    action=argparse.BooleanOptionalAction,
    default=False,
    required=False
  )
  parser.add_argument(
    "--snpsites",
    help="Output variable sites.",
    action=argparse.BooleanOptionalAction,
    default=False,
    required=False
  )
  parser.add_argument(
      "--alignment",
      "-a",
      help="Provide path and filename of alignment",
      required=True,
  )
  args = parser.parse_args(a)
  return args


if __name__=='__main__':
  bcdir = os.path.dirname(os.path.abspath(__file__))
  args = add_args(sys.argv[1:])
  alignment = args.alignment

  processes = ''
  if args.proc:
    processes = f' -t {args.proc}'
  
  if args.strict:
    if args.lowmem:
      command = f'{bcdir}/bin/BactCore-lm-strict{processes} {alignment} > {alignment}.bc'
      subprocess.run(command, shell=True, check=True)
    else:
      command = f'{bcdir}/bin/BactCore-strict{processes} {alignment} > {alignment}.bc'
      subprocess.run(command, shell=True, check=True)
  else:
    if args.lowmem:
      command = f'{bcdir}/bin/BactCore-lm{processes} {alignment} > {alignment}.bc'
      subprocess.run(command, shell=True, check=True)
    else:
      command = f'{bcdir}/bin/BactCore_binary{processes} {alignment} > {alignment}.bc'
      subprocess.run(command, shell=True, check=True)
  if args.snpsites:
    command = f'{bcdir}/bin/BactCore-snps{processes} {alignment}.bc > {alignment}.snpsites'
    subprocess.run(command, shell=True, check=True)

    
